services:
  postgres:
    image: postgres:18
    container_name: groupbuy-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: groupbuy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/18/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: