# ===== DATABASE =====
spring.datasource.url=jdbc:postgresql://localhost:5432/groupbuy
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== THYMELEAF =====
spring.thymeleaf.cache=false

# ===== SERVER =====
server.port=8080

# ===== CURRENCY =====
groupbuy.currency.base=RUB
groupbuy.currency.api.base-url=https://v6.exchangerate-api.com/v6
groupbuy.currency.api_token=${GROUPBUY_CURRENCY_API_TOKEN:}

# ===== LOGGING =====
logging.level.org.springframework.security=DEBUG
